name: build

on: [push, pull_request]

env:
  IDE_VERSION: 1.8.19
  TEENSY_VERSION: 158
  IDE_LOCATION: /usr/local/share/arduino

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compilation: ['Serial: SAT0']
        include:
          - compilation: 'Serial: SAT0_Master'
            sketch: "./software/SAT0_Master/SAT0_Master.ino"
            usb_mode: serial
          - compilation: 'Serial: SAT0_Ground'
            sketch: "./software/SAT0_Master/SAT0_Ground.ino"
            usb_mode: serial
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Arduino IDE
        run: |
          wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
          tar xf arduino-$IDE_VERSION-linux64.tar.xz
          sudo mv arduino-$IDE_VERSION /usr/local/share/arduino
          sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
          rm arduino-$IDE_VERSION-linux64.tar.xz

      - name: Install Teensyduino
        run: |
          wget https://www.pjrc.com/teensy/td_$TEENSY_VERSION/TeensyduinoInstall.linux64;
          chmod +x ./TeensyduinoInstall.linux64;
          sudo ./TeensyduinoInstall.linux64 --dir=/usr/local/share/arduino;
          rm ./TeensyduinoInstall.linux64;

      - name: Install libraries
        run: arduino-cli lib install "RingBufCPP@1.3"

#      - name: Teensy 3.5
#        run: arduino --verify --board teensy:avr:teensy35:usb=${{ matrix.usb_mode }},speed=120,opt=o2std,keys=en-us ${{ matrix.sketch }};

      - name: Teensy 3.6
        run: arduino --verify --board teensy:avr:teensy36:usb=${{ matrix.usb_mode }},speed=180,opt=o2std,keys=en-us ${{ matrix.sketch }};

      - name: Teensy 4.1
        run: arduino --verify --board teensy:avr:teensy41:usb=${{ matrix.usb_mode }},speed=600,opt=o2std,keys=en-us ${{ matrix.sketch }};